sudo: false
dist: trusty
language: node_js
node_js:
- 4
- 6
- 8
services:
  - redis-server

stages:
  - test
  - name: npm publish
    if: tag =~ ^v

before_install:
  # update npm on node 4, which installs/makes assertions on peerDependencies
  - if [[ `npm -v` = 2* ]]; then npm i -g npm@5; fi

after_success:
  - npm run report-cov

jobs:
  include:
    - stage: npm publish
      node_js: 8
      env:
        # d2l-travis-deploy: 11af......2679
        - secure: ONTkpjSenapCejlqk/z+QtpFckkBG2/hWSlND6b+Q0CoFgNMBgXGxgyCkHKG74qDTmZWsBv6SY/6vh33BvuBfGX+bOELj7Y48bTraunsbIRK75/b31480JVx8YDomFaOhYUZDWd+xgOdWcpmii3iOmjl6u4tKyASbKu8A0CwnGeqanMu7DJIakgNX3qVwSN09O2fvNnt6VAOzsmSzcxQNCrJZd3Rm6pJm93l7oZm8lRBY/wp82SM0i/oKRbMmyqrv4m3+q3IPo3vPBjsYgPeT+gnv6dAuat+d0xRWv/lV7WJuV4XtT/iIjzPJchsK5Ha8n/nzg0lBjB7a1rGU8F0NjQ87ue5BtmF0RPDVVY79q9yGSXmrkmYPz0TqeS2AgP6MObckErap08ZGALkQsRLzSWMAK+2JurBZ9oVB/bWniIJvRBAUproJU6qFktJrqOoVy25uweQ/QCdkCkGbQOLDmQqzrOjEle+cz6X5WprsNb6Ixhk1swqjepsf+xvkEmP3YJuE3CzaaO6EOwhGg2Em2acpqJL28Ih6k4KicZp60nMMVin9XYFCpllbOKL6ClkNHXLjGpSDLYanxUIiZXiGDp4abIJDG9BI3kFHtt7TSjNaDGPSX5DMho/mUB4zdKaeOgQ/Z9QEZXA4rO/FmLTHFcERZd/Lc2YxuxRmHSNP9w=
      script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - ./bin/do-release.sh
